In [4]:

from pyjstat import pyjstat
import requests

post_url = 'https://data.ssb.no/api/v0/no/table/07459'
query = {"query":[{"code":"Region","selection":{"filter":"item","values":["0301","1103","5001"]}},
                   {"code":"Kjonn","selection":{"filter":"item","values":["1","2"]}},
                   {"code":"Alder","selection":{"filter":"item","values":["000","001","002"]}},
                   {"code":"ContentsCode","selection":{"filter":"item","values":["Personer1"]}},
                   {"code":"Tid","selection":{"filter":"item","values":["2019","2020","2021"]}}
                  ],
          "response":{"format":"json-stat2"}}
result = requests.post(post_url, json=query)

In [5]:
dataset = pyjstat.Dataset.read(result.text)
tittel = dataset['label']
print("Keys:", dataset.keys())
befolkning_id = dataset.write('dataframe', naming='id')
befolkning = dataset.write('dataframe')
befolkning['kommune'] = befolkning_id['Region']+ ' '+ befolkning['region']
befolkning_ny = befolkning[['kommune', 'kjønn', 'alder', 'år', 'value']]
befolkning

Keys: odict_keys(['class', 'label', 'source', 'updated', 'id', 'size', 'dimension', 'value', 'role', 'version', 'extension'])

,region,kjønn,alder,statistikkvariabel,år,value,kommune
0,Oslo,Menn,0 år,Personer,2019,4523,0301 Oslo
1,Oslo,Menn,0 år,Personer,2020,4647,0301 Oslo
2,Oslo,Menn,0 år,Personer,2021,4498,0301 Oslo
3,Oslo,Menn,1 år,Personer,2019,4507,0301 Oslo
4,Oslo,Menn,1 år,Personer,2020,4283,0301 Oslo
5,Oslo,Menn,1 år,Personer,2021,4320,0301 Oslo
6,Oslo,Menn,2 år,Personer,2019,4463,0301 Oslo
7,Oslo,Menn,2 år,Personer,2020,4280,0301 Oslo
8,Oslo,Menn,2 år,Personer,2021,3973,0301 Oslo
9,Oslo,Kvinner,0 år,Personer,2019,4479,0301 Oslo
10,Oslo,Kvinner,0 år,Personer,2020,4454,0301 Oslo
11,Oslo,Kvinner,0 år,Personer,2021,4345,0301 Oslo
12,Oslo,Kvinner,1 år,Personer,2019,4186,0301 Oslo
13,Oslo,Kvinner,1 år,Personer,2020,4159,0301 Oslo
14,Oslo,Kvinner,1 år,Personer,2021,4166,0301 Oslo
15,Oslo,Kvinner,2 år,Personer,2019,4144,0301 Oslo
16,Oslo,Kvinner,2 år,Personer,2020,3975,0301 Oslo
17,Oslo,Kvinner,2 år,Personer,2021,3902,0301 Oslo
18,Stavanger,Menn,0 år,Personer,2019,770,1103 Stavanger
19,Stavanger,Menn,0 år,Personer,2020,842,1103 Stavanger
20,Stavanger,Menn,0 år,Personer,2021,768,1103 Stavanger
21,Stavanger,Menn,1 år,Personer,2019,822,1103 Stavanger
22,Stavanger,Menn,1 år,Personer,2020,816,1103 Stavanger
23,Stavanger,Menn,1 år,Personer,2021,836,1103 Stavanger
24,Stavanger,Menn,2 år,Personer,2019,846,1103 Stavanger
25,Stavanger,Menn,2 år,Personer,2020,868,1103 Stavanger
26,Stavanger,Menn,2 år,Personer,2021,796,1103 Stavanger
27,Stavanger,Kvinner,0 år,Personer,2019,766,1103 Stavanger
28,Stavanger,Kvinner,0 år,Personer,2020,760,1103 Stavanger
29,Stavanger,Kvinner,0 år,Personer,2021,781,1103 Stavanger
30,Stavanger,Kvinner,1 år,Personer,2019,816,1103 Stavanger
31,Stavanger,Kvinner,1 år,Personer,2020,807,1103 Stavanger
32,Stavanger,Kvinner,1 år,Personer,2021,744,1103 Stavanger
33,Stavanger,Kvinner,2 år,Personer,2019,821,1103 Stavanger
34,Stavanger,Kvinner,2 år,Personer,2020,871,1103 Stavanger
35,Stavanger,Kvinner,2 år,Personer,2021,807,1103 Stavanger
36,Trondheim - Tråante,Menn,0 år,Personer,2019,1059,5001 Trondheim - Tråante
37,Trondheim - Tråante,Menn,0 år,Personer,2020,1194,5001 Trondheim - Tråante
38,Trondheim - Tråante,Menn,0 år,Personer,2021,1060,5001 Trondheim - Tråante
39,Trondheim - Tråante,Menn,1 år,Personer,2019,1117,5001 Trondheim - Tråante
40,Trondheim - Tråante,Menn,1 år,Personer,2020,1062,5001 Trondheim - Tråante
41,Trondheim - Tråante,Menn,1 år,Personer,2021,1173,5001 Trondheim - Tråante
42,Trondheim - Tråante,Menn,2 år,Personer,2019,1159,5001 Trondheim - Tråante
43,Trondheim - Tråante,Menn,2 år,Personer,2020,1157,5001 Trondheim - Tråante
44,Trondheim - Tråante,Menn,2 år,Personer,2021,1079,5001 Trondheim - Tråante
45,Trondheim - Tråante,Kvinner,0 år,Personer,2019,1023,5001 Trondheim - Tråante
46,Trondheim - Tråante,Kvinner,0 år,Personer,2020,1061,5001 Trondheim - Tråante
47,Trondheim - Tråante,Kvinner,0 år,Personer,2021,1036,5001 Trondheim - Tråante
48,Trondheim - Tråante,Kvinner,1 år,Personer,2019,1069,5001 Trondheim - Tråante
49,Trondheim - Tråante,Kvinner,1 år,Personer,2020,1053,5001 Trondheim - Tråante
50,Trondheim - Tråante,Kvinner,1 år,Personer,2021,1037,5001 Trondheim - Tråante
51,Trondheim - Tråante,Kvinner,2 år,Personer,2019,1096,5001 Trondheim - Tråante
52,Trondheim - Tråante,Kvinner,2 år,Personer,2020,1095,5001 Trondheim - Tråante
53,Trondheim - Tråante,Kvinner,2 år,Personer,2021,1039,5001 Trondheim - Tråante

In [6]:
json_q1 = {"query":
           [{"code":"Region","selection":{"filter":"agg:KommSummer","values":["K-0301","K-3002"]}},
            {"code":"Kjonn","selection":{"filter":"item","values":["1","2"]}},
            {"code":"Alder","selection":{"filter": "agg:FemAarigGruppering", "values":["F00-04", "F05-09"]}},
            {"code":"ContentsCode","selection":{"filter":"item","values":["Personer1"]}},
            {"code":"Tid","selection":{"filter":"item","values":["2019","2020","2021"]}}
           ],
           "response":{"format":"json-stat2"}}

# samme med ny spørring
res1 = requests.post(post_url, json=json_q1)
ds1 = pyjstat.Dataset.read(res1.text)
befolkning1 = ds1.write('dataframe')
befolkning_id1 = ds1.write('dataframe', naming='id')
befolkning1

   region    kjønn   alder statistikkvariabel    år  value
0    Moss     Menn  0-4 år           Personer  2019   1248
1    Moss     Menn  0-4 år           Personer  2020   1201
2    Moss     Menn  0-4 år           Personer  2021   1151
3    Moss     Menn  5-9 år           Personer  2019   1377
4    Moss     Menn  5-9 år           Personer  2020   1372
5    Moss     Menn  5-9 år           Personer  2021   1393
6    Moss  Kvinner  0-4 år           Personer  2019   1112
7    Moss  Kvinner  0-4 år           Personer  2020   1094
8    Moss  Kvinner  0-4 år           Personer  2021   1094
9    Moss  Kvinner  5-9 år           Personer  2019   1416
10   Moss  Kvinner  5-9 år           Personer  2020   1354
11   Moss  Kvinner  5-9 år           Personer  2021   1318
12   Oslo     Menn  0-4 år           Personer  2019  21895
13   Oslo     Menn  0-4 år           Personer  2020  21500
14   Oslo     Menn  0-4 år           Personer  2021  20871
15   Oslo     Menn  5-9 år           Personer  2019  19189
16   Oslo     Menn  5-9 år           Personer  2020  19231
17   Oslo     Menn  5-9 år           Personer  2021  19068
18   Oslo  Kvinner  0-4 år           Personer  2019  20556
19   Oslo  Kvinner  0-4 år           Personer  2020  20276
20   Oslo  Kvinner  0-4 år           Personer  2021  19920
21   Oslo  Kvinner  5-9 år           Personer  2019  18409
22   Oslo  Kvinner  5-9 år           Personer  2020  18288
23   Oslo  Kvinner  5-9 år           Personer  2021  17950

In [7]:
import json

with open ("ssbapi_table_06913.json", 'r') as file:
    ssbapi_query = json.load(file)

query = ssbapi_query["queryObj"]
post_url = ssbapi_query["postUrl"]
tabellnummer = ssbapi_query["tableIdForQuery"]

resultat = requests.post(post_url,json=query)

In [9]:
dataset = pyjstat.Dataset.read(resultat.text)
dataframe = dataset.write('dataframe')
dataframe_id = dataset.write('dataframe', naming='id')
df_ny = dataframe.set_index(['region', 'år'])
#df_ny.loc["Halden"].query("statistikkvariabel == 'Døde' and value < 250")
statvar = set(df_ny["statistikkvariabel"])
df_ny = df_ny.pivot(columns="statistikkvariabel", values='value')
dataframe

                            region    statistikkvariabel    år    value
0                           Halden  Befolkning 1. januar  1951  23388.0
1                           Halden  Befolkning 1. januar  1952  23690.0
2                           Halden  Befolkning 1. januar  1953  24032.0
3                           Halden  Befolkning 1. januar  1954  24177.0
4                           Halden  Befolkning 1. januar  1955  24454.0
...                            ...                   ...   ...      ...
210235  Delte kommuner og uoppgitt         Folketilvekst  2019   -109.0
210236  Delte kommuner og uoppgitt         Folketilvekst  2020      0.0
210237  Delte kommuner og uoppgitt         Folketilvekst  2021      0.0
210238  Delte kommuner og uoppgitt         Folketilvekst  2022      0.0
210239  Delte kommuner og uoppgitt         Folketilvekst  2023      0.0

[210240 rows x 4 columns]