In [1]:
import pandas as pd

data = { "alder": [1,2,3], "navn": ["Kåre", "Kon", "Radi"]}
df = pd.DataFrame(data)

In [4]:
data2 = [{"alder": 1, "navn": "Kåre"}, {"alder": 4, "navn": "JAY"}, {"alder": 102, "navn": "BOOP"}]
pd.DataFrame(data2)

   alder  navn
0      1  Kåre
1      4   JAY
2    102  BOOP

In [5]:
df

   alder  navn
0      1  Kåre
1      2   Kon
2      3  Radi