In [19]:
import pandas as pd

df_moodle = pd.read_csv("moodleres.csv")
df_bb = pd.read_csv("bb.csv")
df_bb

         Etternavn         Fornavn Brukernavn  Student-ID  Unnamed: 4
0            Aadde          Petter   petteaad      109744         NaN
1              Aas    Edvard Tynes   edvardta      109765         NaN
2         Adolfsen     Simon Anker   simonado      109719         NaN
3         Amundsen    Albert Bakke   alberbam      109372         NaN
4         Amundsen    Amanda Oddli   amandaam      545602         NaN
..             ...             ...        ...         ...         ...
101        Ulstein          Markus   markusul      109728         NaN
102       Ulvestad  Andreas Hovden    andrhul      109389         NaN
103          Vatne     Silje Eiken   siljeeva      108447         NaN
104  Zahl-Brathaug            Saga      sagaz      590413         NaN
105          Årdal        Per Olav    peroaar      109370         NaN

[106 rows x 5 columns]

In [59]:
df_moodle = df_moodle.rename(columns={"First name": "Fornavn", "Last name": "Etternavn"})

df = pd.merge(df_moodle, df_bb, on=["Fornavn", "Etternavn"])
df = df.replace("-", "0.0")

df  = df.astype({"Quiz: Øving 1 - Variabler og datatyper (Real)": "float64", "Quiz: Øving 2 - Funksjoner, løkker og lister (Real)": "float64"})
df["GodkjenningB"] = (df["Quiz: Øving 1 - Variabler og datatyper (Real)"]>=7.5) & (df["Quiz: Øving 2 - Funksjoner, løkker og lister (Real)"]>=7.5)
df["Godkjenning"] = df["GodkjenningB"].map(lambda x: "Godkjent" if x else "Ikke godkjent")
df_moodle.query("Etternavn == 'Sagflaat'")

,Fornavn,Etternavn,ID number,Institution,Department,Email address,"Quiz: Øving 2 - Funksjoner, løkker og lister (Real)",Quiz: Øving 1 - Variabler og datatyper (Real),Last downloaded from this course
85,Nora Oline,Sagflaat,NaN,NaN,NaN,noraosa@stud.ntnu.no,-,10.00,1732706513

In [53]:
import numpy as np
df_fsweb = df[["Fornavn", "Etternavn", "Student-ID", "Godkjenning"]]
df_fsweb.rename(columns={"Student-ID": "Studentnr."}, inplace=True)
df_fsweb.insert(3, "Kandidatnr.", [np.nan]*99)
df_fsweb.to_excel("tilfsweb.xlsx", index=False)
df_fsweb

/tmp/ipykernel_1743572/3728262936.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fsweb.rename(columns={"Student-ID": "Studentnr."}, inplace=True)

            Fornavn      Etternavn  Studentnr.  Kandidatnr. Godkjenning
0            Petter          Aadde      109744          NaN    Godkjent
1      Edvard Tynes            Aas      109765          NaN    Godkjent
2       Simon Anker       Adolfsen      109719          NaN    Godkjent
3      Albert Bakke       Amundsen      109372          NaN    Godkjent
4      Amanda Oddli       Amundsen      545602          NaN    Godkjent
..              ...            ...         ...          ...         ...
94  Christian Teige        Ulstein      507888          NaN    Godkjent
95           Markus        Ulstein      109728          NaN    Godkjent
96   Andreas Hovden       Ulvestad      109389          NaN    Godkjent
97      Silje Eiken          Vatne      108447          NaN    Godkjent
98             Saga  Zahl-Brathaug      590413          NaN    Godkjent

[99 rows x 5 columns]

In [56]:
df.query("Etternavn == 'Hennøen'")

,Fornavn,Etternavn,ID number,Institution,Department,Email address,"Quiz: Øving 2 - Funksjoner, løkker og lister (Real)",Quiz: Øving 1 - Variabler og datatyper (Real),Last downloaded from this course,Brukernavn,Student-ID,Unnamed: 4,GodkjenningB,Godkjenning
44,Marianne,Hennøen,NaN,NaN,NaN,marhenn@stud.ntnu.no,0.0,10.0,1732706513,marhenn,279473,NaN,False,Ikke godkjent