In [31]:
import pandas as pd

dfm = pd.read_csv("moodle2.csv")
dfm = dfm.replace("-", 0.0)
dfm = dfm.astype({"Quiz: Øving 2 - Funksjoner, løkker og lister (Real)": "float64",
           "Quiz: Øving 1 - Variabler og datatyper (Real)": "float64"})

dfm["pass"]  = (dfm["Quiz: Øving 1 - Variabler og datatyper (Real)"] >= 7.5) & (dfm["Quiz: Øving 2 - Funksjoner, løkker og lister (Real)"] >= 7.5)

dfm["Godkjent"] = dfm["pass"].map(lambda x: "Godkjent" if x else "Ikke godkjent")

dfm.query("`Last name` == 'Grønmo'")
#dfm.query("`First name`== 'Fredrik'")

               First name Last name  ...   pass       Godkjent
42  Christopher Reinfjord    Grønmo  ...  False  Ikke godkjent

[1 rows x 12 columns]

In [34]:
for e in dfm["Email address"]:
    brukernavn =(e.split("@"))

brukernavn = [e.split("@") for e in dfm["Email address"]]
for b in brukernavn:
    if "." in b[0]:
        print(b)

dfm.query("Godkjent == 'Ikke godkjent'").sort_values(by="Last name")

['morten.a.biering', 'ntnu.no']
['ali.deldar', 'ntnu.no']

                       First name Last name  ...   pass       Godkjent
5               Avnit-Simon Singh     Anand  ...  False  Ikke godkjent
16                Camilla Van Thy       Bui  ...  False  Ikke godkjent
21                            Ali    Deldar  ...  False  Ikke godkjent
32                         Marcus      Frey  ...  False  Ikke godkjent
42          Christopher Reinfjord    Grønmo  ...  False  Ikke godkjent
45                  Eskild Solbak    Hansen  ...  False  Ikke godkjent
49                       Marianne   Hennøen  ...  False  Ikke godkjent
52   Abduljabbaar Mohamoud Ismail       Hir  ...  False  Ikke godkjent
54                 Ane Kirksæther   Hofstad  ...  False  Ikke godkjent
72                         Helene       Moa  ...  False  Ikke godkjent
73                           Rune  Molander  ...  False  Ikke godkjent
81                 Magnus Myrseth  Rekkedal  ...  False  Ikke godkjent
85                     Nora Oline  Sagflaat  ...  False  Ikke godkjent
88                         Martin    Skrove  ...  False  Ikke godkjent
104                           Oda   Ulvenes  ...  False  Ikke godkjent
6                        Per Olav     Årdal  ...  False  Ikke godkjent

[16 rows x 12 columns]